### ISSUE TITLE
Unable to run it with python 3

### ISSUE THREAD

**Issue by lijierui** [idejie/bottom-up-attention-colab#4]
Thanks so much for the repo, great work! However, after I followed your steps to install Caffe and cv2, it's installed with the default python 3 instead of python 2.7 since colab deprecated python 2 already. 
I can manage to run generate_tsv_36.py by enforcing "!python2 generate_tsv_36.py". But the Caffe and cv2 packages are not installed in the colab python2 directory. 
Do you have any idea how I may set up the environment for python 2 and solve this? Thanks again!

**Comment by idejie** [comment]
Hi @lijierui ,

Sorry for this late reply, because of my busy work.

It's too complex to migrate to a new version(caffe or python) .

So I forked and modified a new object detection framework. I think the new one is better.

You can try it！

***support the latest pytorch version***: https://github.com/idejie/scene_graph_benchmark/tree/torch1.12

Best Wishes,
Dejie Yang

**Comment by lijierui** [comment]
Thank you so much for the follow-up. I was looking for a scene graph construction codebase months ago. This seems a good point to start. 
BTW, I resolved the bottom-up-attention running issue by switching to a PyTorch version here: https://github.com/airsplay/py-bottom-up-attention , which copies the exact weights of the FastRCNN from Caffe to PyTorch model. Might be helpful for anyone who wishes to get a test set representation from the ORIGINAL BOTTOM-UP-ATTENTION weights.
Thanks again! Will check the scenegraph codebase when I had a chance.
